version: '3.9'

services:
  webvulnscanner:
    build:
      context: .
      dockerfile: DockerFile
    container_name: webvulnscanner
    volumes:
      - .:/webvulnscanner
    working_dir: /webvulnscanner
    command: python scanner/main.py
    